{
  pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.my.programs.development.editors.vscode;
in
{
  options.my.programs.development.editors.vscode = {
    enable = lib.mkEnableOption "Enable VSCode";
  };

  config = lib.mkIf cfg.enable {
    programs.vscode = {
      enable = true;
      profiles.default = {
        extensions = with pkgs.vscode-extensions; [
          bbenoist.nix
          golang.go
          mkhl.direnv
          ms-kubernetes-tools.vscode-kubernetes-tools
          ms-vsliveshare.vsliveshare
          ms-python.python
          redhat.vscode-yaml
          yzhang.markdown-all-in-one

          catppuccin.catppuccin-vsc
        ];
        # keybindings generated by:
        # curl -s https://raw.githubusercontent.com/kasecato/vscode-intellij-idea-keybindings/a7cd83558d0d6a8a5a3656c760bc4368ffab323b/package.json \
        #   | jq '.contributes.keybindings' > jetbrains-keybindings.json
        keybindings = ./jetbrains-keybindings.json;
        userSettings = {
          # updates
          "update.showReleaseNotes" = false;
          "update.mode" = "none";
          "extensions.autoCheckUpdates" = false;
          "extensions.autoUpdate" = false;

          # general
          "workbench.startupEditor" = "none";
          "workbench.colorTheme" = "Catppuccin Mocha";
          "editor.fontFamily" = "FiraCode Nerd Font, monospace";
          "editor.fontLigatures" = true;

          # extensions
          "redhat.telemetry.enabled" = false;
          "vs-kubernetes" = {
            "vs-kubernetes.crd-code-completion" = "enabled";
          };
        };
      };
    };
  };
}
